CREATE TABLE IF NOT EXISTS nurse_diagnoses (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(500) NOT NULL UNIQUE,
  description TEXT,
  min_criteria_count INT NOT NULL DEFAULT 2,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

